### ISSUE TITLE
Proposal to do list (before Nov. 18)

### ISSUE THREAD

**Issue by alyciakb** [UBC-MDS/DSCI_522_Alberta-Oil-Spills#1]
- Remove company name, no longer a feature
- Refine question to be what are the best predictors
- Update analysis plan to reflect updated question
- provide code file for loading CSV
- update folder structure within repository

**Comment by huijuechen** [comment]
Remove company name, no longer a feature - done Nov 15
Refine question to be what are the best predictors - done Nov 18, changed to hypothesis tests instead of prediction.
Update analysis plan to reflect updated question - done Nov 18
provide code file for loading CSV - done Nov 18, updated to R script
update folder structure within repository -done Nov 17
